### ISSUE TITLE
feature: porting delete table from stonedb-5.7-dev

### ISSUE THREAD

**Issue by hustjieke** [stoneatom/stonedb#702]
**Is your feature request related to a problem? Please describe.**

Running mtr test: delete.test   delete_all_rows.test
```
CURRENT_TEST: tianmu.delete
mysqltest: At line 54: Query 'DELETE from t1 where a=1 limit 1' failed.
ERROR 1031 (HY000): Table storage engine for 't1' doesn't have this option
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hustjieke** [comment]
related issues: 

- [x] #344 with commit id: 50865ef7cf0f96f821dfdc92e5a39fc76042b802
- [x] #345 #348 with commit id in stonedb-5.7: 0be195aec7fb674d11a86e46cdf3e9fa2d4abf8d
- [x] #510 with commit id: 08f5ae57df40ce043fa5bf724e86c0df5b65fb9a
- [x] #579 with commit id: 7789a52c059fee9b86f1ef205a910c854787a319
- [x] #663  with commit id: ea99be984b8c883d507ec781ce46ba445799eb3b
- [x] #678 with commit id 24a27db6fdfdf9ae2225f4460a9b2eb9fc08e5b3
